Building DAG of jobs...
shared_storage_local_copies: True
remote_exec: False
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job               count
--------------  -------
all                   1
samtools_merge        1
total                 2

Resources before job selection: {'_cores': 1, '_nodes': 9223372036854775807}
Ready jobs (1)
Select jobs to execute...
Using greedy selector because only single job has to be scheduled.
Selected jobs (1)
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}
Execute 1 jobs...

[Thu Feb 29 20:27:43 2024]
localrule samtools_merge:
    input: A.bam, B.bam, D.bam, E.bam, F.bam, G.bam, H.bam, I.bam, J.bam
    output: merged.bam
    jobid: 1
    reason: Missing output files: merged.bam
    resources: tmpdir=/var/folders/7g/mh6jk4p54_v368myk7s9h_nh0000gn/T

Full Traceback (most recent call last):
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/executors/local.py", line 420, in run_wrapper
    run(
  File "/Users/mvandestreek/Library/CloudStorage/OneDrive-HanzehogeschoolGroningen/HanzeHogeschool/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/tutorial_02/workflow/Snakefile", line 71, in __rule_samtools_merge
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/wrapper.py", line 110, in wrapper
    script(
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/script/__init__.py", line 1550, in script
    executor.evaluate()
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/script/__init__.py", line 455, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/script/__init__.py", line 684, in execute_script
    self._execute_cmd(
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/script/__init__.py", line 486, in _execute_cmd
    return shell(
           ^^^^^^
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/shell.py", line 297, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  /Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/bin/python3.12 /Users/mvandestreek/Library/CloudStorage/OneDrive-HanzehogeschoolGroningen/HanzeHogeschool/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/tutorial_02/.snakemake/scripts/tmp7uuatf6s.wrapper.py' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/executors/local.py", line 420, in run_wrapper
    run(
  File "/Users/mvandestreek/Library/CloudStorage/OneDrive-HanzehogeschoolGroningen/HanzeHogeschool/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/tutorial_02/workflow/Snakefile", line 71, in __rule_samtools_merge
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/wrapper.py", line 110, in wrapper
    script(
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/script/__init__.py", line 1550, in script
    executor.evaluate()
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/script/__init__.py", line 455, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/script/__init__.py", line 684, in execute_script
    self._execute_cmd(
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/script/__init__.py", line 486, in _execute_cmd
    return shell(
           ^^^^^^
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/shell.py", line 297, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  /Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/bin/python3.12 /Users/mvandestreek/Library/CloudStorage/OneDrive-HanzehogeschoolGroningen/HanzeHogeschool/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/tutorial_02/.snakemake/scripts/tmp7uuatf6s.wrapper.py' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/executors/local.py", line 259, in _callback
    raise ex
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/executors/local.py", line 245, in cached_or_run
    run_func(*args)
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/executors/local.py", line 456, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /Users/mvandestreek/Library/CloudStorage/OneDrive-HanzehogeschoolGroningen/HanzeHogeschool/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/tutorial_02/workflow/Snakefile, line 29:
Command 'set -euo pipefail;  /Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/bin/python3.12 /Users/mvandestreek/Library/CloudStorage/OneDrive-HanzehogeschoolGroningen/HanzeHogeschool/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/tutorial_02/.snakemake/scripts/tmp7uuatf6s.wrapper.py' returned non-zero exit status 1.

RuleException:
CalledProcessError in file /Users/mvandestreek/Library/CloudStorage/OneDrive-HanzehogeschoolGroningen/HanzeHogeschool/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/tutorial_02/workflow/Snakefile, line 29:
Command 'set -euo pipefail;  /Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/bin/python3.12 /Users/mvandestreek/Library/CloudStorage/OneDrive-HanzehogeschoolGroningen/HanzeHogeschool/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/tutorial_02/.snakemake/scripts/tmp7uuatf6s.wrapper.py' returned non-zero exit status 1.
[Thu Feb 29 20:27:45 2024]
Error in rule samtools_merge:
    jobid: 1
    input: A.bam, B.bam, D.bam, E.bam, F.bam, G.bam, H.bam, I.bam, J.bam
    output: merged.bam
    conda-env: /Users/mvandestreek/Library/CloudStorage/OneDrive-HanzehogeschoolGroningen/HanzeHogeschool/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/tutorial_02/.snakemake/conda/1e4519dd03ef09f301d4f04b42038d2d_

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-02-29T202743.541072.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/cli.py", line 1975, in args_to_api
    dag_api.execute_workflow(
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/api.py", line 588, in execute_workflow
    workflow.execute(
  File "/Users/mvandestreek/miniconda3/envs/new_snake_env_les_1/lib/python3.12/site-packages/snakemake/workflow.py", line 1265, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
